# Generated by Django 6.0.1 on 2026-02-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_rename_product_billitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='name',
            new_name='product',
        ),
    ]
