# Generated by Django 6.0.1 on 2026-03-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0006_rename_name_billitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing_app.bill'),
        ),
    ]
