# Generated by Django 6.0.1 on 2026-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0009_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='final_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
