# Generated by Django 6.0.1 on 2026-02-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_alter_bill_customer_name_alter_bill_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='total_amound',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='Bill',
            new_name='bill',
        ),
    ]
