# Generated by Django 6.0.1 on 2026-02-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_rename_discount_bill_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing_app.product'),
            preserve_default=False,
        ),
    ]
