# Generated by Django 6.0.1 on 2026-02-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_billitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitem',
            old_name='Product',
            new_name='name',
        ),
    ]
